version: '3.8'

services:
  app:
    container_name: app_container
    build: ./
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database
    networks:
      - app_network

  database:
    container_name: database_container
    image: postgres:latest
    environment:
      POSTGRES_USER: barbershop
      POSTGRES_PASSWORD: barbershop456498
      POSTGRES_DB: barbershop
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app_network

# TODO Вынести migration в отдельный контейнер

volumes:
  api:
  database_postgres:

networks:
  app_network:
    driver: bridge