version: '3.8'

services:
  app:
    container_name: app_container
    build: ./
    env_file:
      - .env
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database
    networks:
      - app_network

  database:
    container_name: database_container
    image: postgres:latest
    environment:
      TZ: 'Asia/Vladivostok'
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  api:
  database_postgres:

networks:
  app_network:
    driver: bridge